main/urls.py
from django.urls import path
from .views import *

app_name = 'main'

urlpatterns = [
    path('', home, name='home'),

    path('tariffs/', tariffs, name='tariffs'),
    path('get_tariff/<id>', get_tariff, name='get_tariff'),
    path('remove_tariff/', remove_tariff, name='remove_tariff'),
    path('contacts/', Contacts.as_view(), name='contacts'),
    path('contacts/success', contact_success, name='contact_success'),


    path('lk/', view_profile, name='profile'),
    path('lk/requisites/', view_requisites, name='view_requisites'),
    path('lk/requisites/pay/', pay_tariff, name='pay'),
    path('lk/tariffs_history/', get_tariffs_history, name='tariffs_history'),
    path('lk/tariffs_history/id=<id>', view_decline, name='view_decline'),
    path('lk/complaints_history/', get_complaints_history, name='complaints_history'),
    path('lk/addcomplaint', login_required(AddComplaint.as_view()), name='addcomplaint'),

    path('engineer/', engineer_profile, name='engineer_lk'),
    path('engineer/requests/', connection_requests, name='connetion_requests'),
    path('engineer/requests/id=<id>/', request_detail, name='request_detail'),
    path('engineer/requests/id=<id>/accept/', accept_request, name='request_accept'),
    path('engineer/complaints/', complaints_list, name='complaints_list'),
    path('engineer/complaints/id=<id>/', complaint_reply, name='complaints_reply'),

    path('login/', LoginUser.as_view(), name='auth'),
    path('register/', RegisterUser.as_view(), name='register'),
    path('logout/', logout_view, name='logout'),
]

practicesystem/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls'))
]

templates/_inc/footer.html
<footer class="footer">
    <div class="container">
        <div class="footer__inner">
            <div class="footer-column">
                <div class="title">Продукты</div>
                <ul class="footer-links">
                    <li class="footer-links__item">
                        <a href="{% url 'main:tariffs' %}">Тарифы</a>
                    </li>
                </ul>
            </div>
            <div class="footer-column">
                <div class="title">Контакты</div>
                <ul class="footer-links">
                    <li class="footer-links__item">
                        <a href="{% url 'main:contacts' %}">Обратная связь</a>
                    </li>
                </ul>
            </div>
            <div class="footer-column-phone">
                <div class="title">Служба поддержки</div>
                <div class="phone">8 800 707 12 12</div>
            </div>
            <div class="footer-column-phone">
                <div class="title">Отдел продаж</div>
                <div class="phone">8 800 707 12 12</div>
            </div>
        </div>
    </div>
</footer>

templates/_inc/header.html
{% load static %}

<header class="header">
    <div class="container">
        <div class="header__inner">

            <div class="logo-container">
                <a href="{% url 'main:home' %}"><img src="{% static 'images/logo.png' %}" alt="" class="logo"></a>
            </div>
            <div class="header__burger">
                <span></span>
            </div>
            <nav class="nav">
                <ul class="">
                </ul>
                <ul class="nav-menu">
                    <li class="nav-menu__item"><a href="{% url 'main:home' %}" class="nav-menu__link">Главная</a></li>
                    <li class="nav-menu__item"><a href="{% url 'main:tariffs' %}" class="nav-menu__link">Тарифы</a></li>
                    <li class="nav-menu__item"><a href="{% url 'main:contacts' %}" class="nav-menu__link">Контакты</a></li>
                </ul>
                <ul class="nav-menu">
                    {% if user.is_authenticated %}
                            <li class="nav-menu__item user-link"><a
                                href="{% url 'main:profile' %}"><img src="{% static 'images/userlogo.png' %}" alt="">{{ user.username }}</a>
                        </li>
                        <li class="nav-menu__item"><a href="{% url 'main:logout' %}">Выход</a></li>
                    {% else %}
                        <li class="nav-menu__item"><a href="{% url 'main:auth' %}"
                                                      class="nav-menu__link">Авторизация</a></li>
                        <li class="nav-menu__item"><a href="{% url 'main:register' %}" class="nav-menu__link">Регистрация</a>
                        </li>
                    {% endif %}
                </ul>
            </nav>
        </div>
    </div>
</header>