main/urls.py
from django.urls import path
from .views import *

app_name = 'main'

urlpatterns = [
    path('', home, name='home'),

    path('tariffs/', tariffs, name='tariffs'),
    path('get_tariff/<id>', get_tariff, name='get_tariff'),
    path('remove_tariff/', remove_tariff, name='remove_tariff'),
    path('contacts/', Contacts.as_view(), name='contacts'),
    path('contacts/success', contact_success, name='contact_success'),


    path('lk/', view_profile, name='profile'),
    path('lk/requisites/', view_requisites, name='view_requisites'),
    path('lk/requisites/pay/', pay_tariff, name='pay'),
    path('lk/tariffs_history/', get_tariffs_history, name='tariffs_history'),
    path('lk/tariffs_history/id=<id>', view_decline, name='view_decline'),
    path('lk/complaints_history/', get_complaints_history, name='complaints_history'),
    path('lk/addcomplaint', login_required(AddComplaint.as_view()), name='addcomplaint'),

    path('engineer/', engineer_profile, name='engineer_lk'),
    path('engineer/requests/', connection_requests, name='connetion_requests'),
    path('engineer/requests/id=<id>/', request_detail, name='request_detail'),
    path('engineer/requests/id=<id>/accept/', accept_request, name='request_accept'),
    path('engineer/complaints/', complaints_list, name='complaints_list'),
    path('engineer/complaints/id=<id>/', complaint_reply, name='complaints_reply'),

    path('login/', LoginUser.as_view(), name='auth'),
    path('register/', RegisterUser.as_view(), name='register'),
    path('logout/', logout_view, name='logout'),
]

practicesystem/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls'))
]

main/forms.py
import re

from django.contrib.auth import authenticate
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from django import forms
from django.core.exceptions import ValidationError
from .models import *


class RegisterUserForm(UserCreationForm):
    username = forms.CharField(label='Логин', widget=forms.TextInput(attrs={
        'autocomplete': 'off',
        'placeholder': 'Логин', }))
    password1 = forms.CharField(label='Пароль', widget=forms.PasswordInput(attrs={
        'autocomplete': 'off',
        'placeholder': 'Пароль', }))
    password2 = forms.CharField(label='Повторите пароль', widget=forms.PasswordInput(attrs={
        'autocomplete': 'off',
        'placeholder': 'Повторите пароль', }))
    first_name = forms.CharField(label='Имя', widget=forms.TextInput(attrs={
        'autocomplete': 'off',
        'placeholder': 'Имя', }))
    last_name = forms.CharField(label='Фамилия', widget=forms.TextInput(attrs={
        'autocomplete': 'off',
        'placeholder': 'Фамилия', }))
    phone = forms.RegexField(
        regex=r'^(\+7|7|8)?[\s\-]?\(?[489][0-9]{2}\)?[\s\-]?[0-9]{3}[\s\-]?[0-9]{2}[\s\-]?[0-9]{2}$',
        widget=forms.TextInput(attrs={'placeholder': 'Номер телефона'}),
        error_messages={'invalid': ('Номер телефона должен быть в формате: +79992345679'), })

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'password1', 'password2', 'phone')

    def clean(self):
        username = self.cleaned_data['username']
        first_name = self.cleaned_data['first_name']
        last_name = self.cleaned_data['last_name']
        phone = self.cleaned_data['phone']

        if len(username) < 5:
            self.add_error('username', 'Логин должен содержать не менее 5 символов')
        if re.search('\d+', first_name) is not None:
            self.add_error('first_name', 'Имя не может содержать цифры')
        if re.search('\d+', last_name) is not None:
            self.add_error('last_name', 'Фамилия не может содержать цифры')


class LoginUserForm(AuthenticationForm):
    username = forms.CharField(label='Логин', widget=forms.TextInput(attrs={
        'autocomplete': 'off',
        'placeholder': 'Логин', }))
    password = forms.CharField(label='Пароль', widget=forms.PasswordInput(attrs={
        'autocomplete': 'off',
        'placeholder': 'Пароль', }))

    def clean(self):
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')
        user = authenticate(self.request, username=username, password=password)
        if user is not None:
            return super(LoginUserForm, self).clean()
        else:
            # the authentication system was unable to verify the username and password
            raise ValidationError("Пожалуйста, проверьте правильность написания логина и пароля.")

    class Meta:
        model = User
        fields = ('username', 'password')


class ComplaintForm(forms.ModelForm):
    class Meta:
        model = Complaint
        fields = ['subject', 'desc']
        widgets = {'user': forms.HiddenInput}


class ContactForm(forms.ModelForm):
    name = forms.CharField(label='Имя', widget=forms.TextInput(attrs={
        'autocomplete': 'off',
        'placeholder': 'Имя', }))
    desc = forms.CharField(label='Фамилия', widget=forms.Textarea(attrs={
        'autocomplete': 'off',
        'placeholder': 'Сообщение', }))
    phone = forms.RegexField(
        regex=r'^(\+7|7|8)?[\s\-]?\(?[489][0-9]{2}\)?[\s\-]?[0-9]{3}[\s\-]?[0-9]{2}[\s\-]?[0-9]{2}$',
        widget=forms.TextInput(attrs={'placeholder': 'Номер телефона'}),
        error_messages={'invalid': ('Номер телефона должен быть в формате: +79992345679'), })

    class Meta:
        model = Contact
        fields = ['name', 'phone', 'desc']

    def clean(self):
        name = self.cleaned_data['name']
        desc = self.cleaned_data['desc']

class RequestForm(forms.ModelForm):
    desc = forms.TextInput()

    class Meta:
        model = TariffHistory
        fields = ('desc',)


class ReplyForm(forms.ModelForm):
    class Meta:
        model = Complaint
        fields = ['answer']

main/views.py
import re
from datetime import timedelta, date

from django.contrib import messages
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LoginView
from django.http import Http404
from django.shortcuts import render, HttpResponse, redirect
from django.urls import reverse_lazy
from django.views.generic import CreateView
from django.contrib.auth.models import Group

from .models import *
from .forms import *
from .admin import *

from .decorators import *


def home(request):
    tariffs = Tariff.objects.all().order_by('-id')[:3]
    return render(request, 'main/index.html', {'tariffs': tariffs})


def tariffs(request):
    tariffs = Tariff.objects.all().order_by('-id')
    return render(request, 'main/cards.html', {'tariffs': tariffs})


class Contacts(CreateView):
    form_class = ContactForm
    template_name = 'main/contacts.html'
    success_url = reverse_lazy('main:contact_success')


def contact_success(request):
    return render(request, 'main/contact-success.html')


@login_required
def get_tariff(request, id):
    response = request.user.usertariff
    if response.tariff:
        return render(request, 'main/tariff-error.html')
    else:
        response.tariff_id = id
        response.is_active = False
        response.is_paid = None
        response.save()
        return render(request, 'main/tariff-success.html')


@login_required
def remove_tariff(request):
    response = request.user.usertariff
    if response.tariff and response.is_active:
        history = TariffHistory(user=request.user, tariff_id=response.tariff_id)
        history.save()
        response.tariff_id = None
        response.is_active = False
        response.save()
        return redirect('main:profile')
    else:
        return redirect('main:profile')


@login_required
def get_tariffs_history(request):
    history = TariffHistory.objects.all().order_by('-id').filter(user=request.user.pk)
    return render(request, 'main/user/history/history_cards.html', {'history': history})


@login_required()
def view_decline(request, id):
    tariff = TariffHistory.objects.get(pk=id)
    return render(request, 'main/user/history/view_decline.html', {'tariff': tariff})


@login_required
def get_complaints_history(request):
    history = Complaint.objects.all().order_by('-id').filter(user=request.user.pk)
    return render(request, 'main/user/history/history_complaints.html', {'history': history})


class AddComplaint(CreateView):
    form_class = ComplaintForm
    template_name = 'main/user/create_complaint.html'
    success_url = reverse_lazy('main:complaints_history')

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super(AddComplaint, self).form_valid(form)


@login_required()
def view_profile(request):
    if User.objects.filter(pk=request.user.pk, groups__name='Инженер').exists():
        return redirect('main:engineer_lk')
    else:
        profile = UserTariff.objects.get(user=request.user)
        return render(request, 'main/user/lk.html', {'profile': profile})


@login_required()
def pay_tariff(request):
    tariff = UserTariff.objects.get(user=request.user)
    if tariff.is_paid == None:
        tariff.is_paid = date.today()
    tariff.is_paid = tariff.is_paid + timedelta(days=30)
    tariff.save()
    return redirect('main:profile')


@login_required()
def view_requisites(request):
    tariff = UserTariff.objects.get(user=request.user)
    return render(request, 'main/user/requisites.html', {'tariff': tariff})


class RegisterUser(CreateView):
    form_class = RegisterUserForm
    template_name = 'main/reg.html'
    success_url = reverse_lazy('main:auth')

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Регистрация'
        return context

    def post(self, request, *args, **kwargs):
        form = RegisterUserForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)

            user.save()

            u = User.objects.get(username=request.POST['username'])
            if not UserTariff.objects.filter(user=u).exists():
                adduser = UserTariff(user=u, tariff_id=None, is_active=False, phone_number=request.POST['phone'])
                adduser.save()

            return redirect('main:auth')
        else:
            return render(request, self.template_name, {'form': form})


class LoginUser(LoginView):
    authentication_form = LoginUserForm
    template_name = 'main/auth.html'
    success_url = reverse_lazy('main:home')

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Авторизация'
        return context

    def get_success_url(self):
        if not UserTariff.objects.filter(user=self.request.user.pk).exists():
            adduser = UserTariff(user=self.request.user, tariff_id=None, is_active=False)
            adduser.save()
        return reverse_lazy('main:home')


def logout_view(request):
    logout(request)
    return redirect('main:home')


@group_required('Инженер')
def engineer_profile(request):
    profile = User.objects.get(pk=request.user.pk)
    return render(request, 'main/engineer/engineer.html', {'profile': profile})


@group_required('Инженер')
def connection_requests(request):
    cards = UserTariff.objects.all().order_by('-id').filter(is_active=False).filter(tariff__isnull=False)
    return render(request, 'main/engineer/requests/connectionrequests.html', {'cards': cards})


@group_required('Инженер')
def request_detail(request, id):
    card = UserTariff.objects.get(pk=id)
    if request.method == 'POST':
        form = RequestForm(request.POST)
        if form.is_valid():
            history = TariffHistory(user=card.user, tariff_id=card.tariff_id, desc=request.POST['desc'],
                                    is_declined=True, engineer=request.user)
            history.save()
            card.tariff_id = None
            card.is_active = False
            card.engineer = None
            card.save()
            return redirect('main:connetion_requests')
        else:
            return render(request, 'main/engineer/requests/requestdetail.html', {'card': card, 'form': form})
    else:
        form = RequestForm()
    return render(request, 'main/engineer/requests/requestdetail.html', {'card': card, 'form': form})


@group_required('Инженер')
def accept_request(request, id):
    card = UserTariff.objects.get(pk=id)
    card.is_active = True
    card.engineer = request.user
    card.save()
    return redirect('main:connetion_requests')


@group_required('Инженер')
def complaints_list(request):
    if request.user.is_superuser:
        complaints = Complaint.objects.all().order_by('-id').filter(status=False)
    else:
        complaints = Complaint.objects.all().order_by('-id').filter(engineer=request.user).filter(status=False)
    return render(request, 'main/engineer/complaints/complaintlist.html', {'complaints': complaints})


@group_required('Инженер')
def complaint_reply(request, id):
    complaint = Complaint.objects.get(pk=id)
    if request.method == 'POST':
        form = ReplyForm(request.POST)
        if form.is_valid():
            complaint.answer = request.POST['answer']
            complaint.status = True
            complaint.save()
            return redirect('main:complaints_list')
        else:
            return render(request, 'main/engineer/complaints/complaint_reply.html',
                          {'complaint': complaint, 'form': form})
    else:
        form = ReplyForm()
    return render(request, 'main/engineer/complaints/complaint_reply.html', {'complaint': complaint, 'form': form})

main/templates/main/auth.html
{% extends 'base.html' %}

{% block title %}
    Авторизация
{% endblock %}

{% block content %}
    <div class="auth">
        <div class="container">
            <div class="auth__inner">
                <div class="no-acc">
                    <div class="no-acc__inner">
                        <div class="text">
                            Все ещё нет аккаунта?
                        </div>
                        <div class="title">
                            Пройдите быструю регистрацию
                        </div>
                        <a class="btn" href="{% url 'main:register' %}">
                            Это абсолютно бесплатно
                        </a>
                    </div>
                </div>
                <div class="form-container">
                    <form class="form-auth" method="POST" action="#">
                        {% csrf_token %}
                        <div class="text">
                            Есть аккаунт?
                        </div>
                        <div class="title">
                            Произведите вход
                        </div>
                        <input type="text" name="username" id="" placeholder="Логин">
                        <input type="password" name="password" id="" placeholder="Пароль">
                        <input type="submit" class="btn-orange" value="Авторизоваться">
                        {% for error in form.non_field_errors %}
                            <div class="error">{{ error }}</div>
                        {% endfor %}
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

main/templates/main/cards.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Тарифы{% endblock %}
{% block content %}
    <div class="container">
        <div class="request">
            {% for tariff in tariffs %}
                <div class="request-card">
                    <div class="title">
                        {{ tariff.title }}
                    </div>
                    <div class="adv">
                        <img src="{% static 'images/web.png' %}" alt=""><span>{{ tariff.speed }} Мбит/с</span>
                    </div>
                    <div class="adv">
                        <img src="{% static 'images/cloud.png' %}"
                             alt=""><span>{{ tariff.cloud }} гб облачного хранилища</span>
                    </div>
                    <div class="desc">
                        {{ tariff.desc }}
                    </div>
                    <div class="price">
                        {{ tariff.price }}Р
                    </div>

                    {% if tariff.is_promotion %}
                        <a class="btn-card btn-phiolet" href="{% url 'main:get_tariff' tariff.id%}">
                            Подключить по акции
                        </a>
                    {% else %}
                        <a class="btn-card btn-orange" href="{% url 'main:get_tariff' tariff.id%}">
                            Подключить
                        </a>
                    {% endif %}
                </div>
            {% endfor %}
        </div>
    </div>

{% endblock %}

main/templates/main/contact-success.html
{% extends 'base.html' %}
{% block title %}Успешно{% endblock %}
{% block content %}
    <div class="content">
        <div class="container">

            <div class="tariff-message">
                <div class="tariff-message__title">Заявка на звонок оформлена</div>
                <div class="tariff-message__text">С вами свяжется оператор</div>
            </div>

        </div>
    </div>

{% endblock %}

main/templates/main/contacts.html
{% extends 'base.html' %}

{% block title %}Обратная связь{% endblock %}

{% block content %}
    <div class="content">
        <div class="container">
            <div class="form-message-container">
                <div class="small-title claim-title">
                    Обратная связь
                </div>

                <div class="small-desc">
                    Пожалуйста, предоставьте некоторую информацию, чтобы оставить сообщение.
                </div>

                <form action="" class="form-message" method="POST">
                    {% csrf_token %}
                    {% for f in form %}
                        {{ f }}
                    {% endfor %}
                    {% if form.errors %}
                        {% for f in form %}
                            <div class="error">{{ f.errors.as_text |cut:"* " }}</div>
                        {% endfor %}
                    {% endif %}
                    <input type="submit" class="btn btn-orange" value="Заказать звонок">
                </form>
            </div>
        </div>
    </div>
{% endblock %}

main/templates/main/index.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Главная{% endblock %}
{% block content %}
    <div class="container">
        <div class="banner">
            <div class="banner-content">
                <div class="hashtag">
                    #СкоростнойИнтернет
                </div>
                <div class="text">
                    Интернет в 10 раз быстрее, чем в нашем колледже
                </div>
                {% if user.is_authenticated %}
                    <a class="btn btn-phiolet" href="{% url 'main:profile' %}">
                        Перейти в личный кабинет
                    </a>
                {% else %}
                    <a class="btn btn-phiolet" href="{% url 'main:register' %}">
                        Зарегистрироваться
                    </a>
                {% endif %}
            </div>
            <div class="banner-gif">
            </div>
        </div>
    </div>

    <div class="container">
        <div class="request-title">
            Отправьте заявку на подключение
        </div>
        <div class="request">
            {% for tariff in tariffs %}
                <div class="request-card">
                    <div class="title">
                        {{ tariff.title }}
                    </div>
                    <div class="adv">
                        <img src="{% static 'images/web.png' %}" alt=""><span>{{ tariff.speed }} Мбит/с</span>
                    </div>
                    <div class="adv">
                        <img src="{% static 'images/cloud.png' %}"
                             alt=""><span>{{ tariff.cloud }} гб облачного хранилища</span>
                    </div>
                    <div class="desc">
                        {{ tariff.desc }}
                    </div>
                    <div class="price">
                        {{ tariff.price }}Р
                    </div>

                    {% if tariff.is_promotion %}
                        <a class="btn-card btn-phiolet" href="{% url 'main:get_tariff' tariff.id %}">
                            Подключить по акции
                        </a>
                    {% else %}
                        <a class="btn-card btn-orange" href="{% url 'main:get_tariff' tariff.id %}">
                            Подключить
                        </a>
                    {% endif %}
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

main/templates/main/reg.html
{% extends 'base.html' %}

{% block title %}
    Регистрация
{% endblock %}

{% block content %}
    <div class="auth">
        <div class="container">
            <div class="auth__inner">
                <div class="no-acc">
                    <div class="no-acc__inner">
                        <div class="text">
                            Есть аккаунт?
                        </div>
                        <div class="title">
                            Авторизуйтесь на платформе
                        </div>
                        <a class="btn" href="{% url 'main:auth' %}">
                            Войти в аккаунт
                        </a>
                    </div>
                </div>
                <div class="form-container">
                    <form class="form-auth" method="POST" action="#">
                        {% csrf_token %}
                        <div class="text">
                            Нет аккаунта?
                        </div>
                        <div class="title">
                            Пройдите регистрацию
                        </div>
                        {% for f in form %}
                            {{ f }}
                        {% endfor %}
                        <input type="submit" class="btn-orange" value="Зарегистрироваться">
                        {% for f in form %}
                            {% for error in f.errors %}
                                <div class="error">{{ error }}</div><br>
                            {% endfor %}
                        {% endfor %}
                        {% for error in form.non_field_errors %}
                            <div class="error">{{ error }}</div>
                        {% endfor %}
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

main/templates/main/tariff-error.html
{% extends 'base.html' %}
{% block title %}Ошибка{% endblock %}
{% block content %}
    <div class="content">
        <div class="container">

            <div class="tariff-message">
                <div class="tariff-message__title">Заявка на тариф не отправлена</div>
                <div class="tariff-message__text">Ожидайте подключения, либо отключите текущий тариф</div>
            </div>

        </div>
    </div>
{% endblock %}

main/templates/main/tariff-success.html
{% extends 'base.html' %}
{% block title %}Успешно{% endblock %}
{% block content %}
    <div class="content">
        <div class="container">

            <div class="tariff-message">
                <div class="tariff-message__title">Заявка на тариф отправлена</div>
                <div class="tariff-message__text">Ожидайте подключения</div>
            </div>

        </div>
    </div>

{% endblock %}